on:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out branch
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: clear project
        run: |
          cd attendance_app
          mvn clean
      - name: compile the project
        run: |
          cd attendance_app
          mvn compile
      - name: run test case
        run: |
          cd attendance_app
          mvn test
      - name: Build with Maven
        run: |
          cd attendance_app
          mvn clean install package
