on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out branch
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: clear project
        run: |
          mvn clean
      - name: compile the project
        run: |
          mvn compile
      - name: run test case
        run: |
          mvn test
      - name: Build with Maven
        run: |
          mvn clean install package
